{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "843f6de2",
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras_tuner import HyperModel\n",
    "import keras_tuner as kt\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "#!pip install keras_tuner\n",
    "#import keras_tuner\n",
    "\n",
    "import keras\n",
    "from keras import models, layers, metrics, Sequential\n",
    "from keras.layers import Dense, BatchNormalization, Dropout\n",
    "import tensorflow as tf\n",
    "from keras.regularizers import l1,l2,l1_l2\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from tensorflow.keras.layers import Input, Dense, Multiply, Concatenate\n",
    "from tensorflow.keras.models import Model\n",
    "\n",
    "import tensorflow as tf\n",
    "import random\n",
    "\n",
    "import keras_tuner\n",
    "from keras_tuner import HyperModel\n",
    "import keras_tuner as kt\n",
    "\n",
    "from sklearn.preprocessing import MinMaxScaler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "2f872a88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "49 49\n"
     ]
    }
   ],
   "source": [
    "merged_latent = pd.read_pickle(\"merged_latent49.pkl\")\n",
    "\n",
    "# merged data 1\n",
    "firm_col = merged_latent.columns.tolist()[18:18+49]\n",
    "latent_col = merged_latent.columns.tolist()[18+49+1:]\n",
    "print(len(firm_col), len(latent_col))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "36c1ffce",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(88347, 49) (88347, 49) (88347,)\n",
      "(31851, 49) (31851, 49) (31851,)\n",
      "(90007, 49) (90007, 49) (90007,)\n"
     ]
    }
   ],
   "source": [
    "df_train = merged_latent[merged_latent.index < pd.Period((str(1995)+\"-1\"),freq='M')]\n",
    "df_val = merged_latent[(merged_latent.index >= pd.Period((str(1995)+\"-1\"),freq='M')) & (merged_latent.index < pd.Period((str(2000)+\"-1\"),freq='M'))]\n",
    "df_test = merged_latent[merged_latent.index >= pd.Period((str(2000)+\"-1\"),freq='M')]\n",
    "\n",
    "merged_train_firm = df_train[firm_col]\n",
    "merged_train_latent = df_train[latent_col]\n",
    "merged_train_y = df_train['predicted_return']\n",
    "print(merged_train_firm.shape, merged_train_latent.shape, merged_train_y.shape)\n",
    "\n",
    "merged_val_firm = df_val[firm_col]\n",
    "merged_val_latent = df_val[latent_col]\n",
    "merged_val_y = df_val['predicted_return']\n",
    "print(merged_val_firm.shape, merged_val_latent.shape, merged_val_y.shape)\n",
    "\n",
    "merged_test_firm = df_test[firm_col]\n",
    "merged_test_latent = df_test[latent_col]\n",
    "merged_test_y = df_test['predicted_return']\n",
    "print(merged_test_firm.shape, merged_test_latent.shape, merged_test_y.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "41f4dbe3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def my_metric_fn(y_true, y_pred):\n",
    "    num = tf.reduce_mean(tf.square(y_true - y_pred))\n",
    "    den = tf.reduce_mean(tf.square(y_true))\n",
    "    return 1 - num / den\n",
    "\n",
    "class MyHyperModel(keras_tuner.HyperModel):\n",
    "    def build(self, hp, n_inputs=49,):\n",
    "        l1_reg = hp.Choice(\"l1_ratio\", [0.,])\n",
    "        l2_reg = hp.Choice(\"l2_ratio\", [0.,0.001])\n",
    "        dropout = hp.Choice(\"dropout\",[ 0., 0.1])\n",
    "        lr = hp.Choice(\"learning_rate\", [0.0001, 0.00005])\n",
    "        \n",
    "        # Define the hidden layers \n",
    "        input1 = Input(shape=(49,))\n",
    "        x1 = Dense(6, activation='relu')(input1)\n",
    "        \n",
    "        # Input 2\n",
    "        input2 = Input(shape=(49,))\n",
    "        x2 = Dense(32, activation='relu',kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(input2)\n",
    "        x2 = Dense(16, activation='relu',kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(x2)\n",
    "        x2 = Dense(8, activation='relu', kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(x2)\n",
    "        x2 = Dense(6, activation='relu', kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(x2)\n",
    "        \n",
    "        merged = Multiply()([x1, x2])\n",
    "        output = Dense(1, activation='linear')(merged)\n",
    " \n",
    "        # Create the model \n",
    "        model = Model(inputs=[input1, input2], outputs=output)\n",
    "        opt = tf.keras.optimizers.Adam(learning_rate=lr)\n",
    "        model.compile(loss='mean_squared_error', optimizer=opt,metrics=[my_metric_fn])\n",
    "        return model\n",
    "    \n",
    "    def fit(self, hp, model, *args, **kwargs):\n",
    "        return model.fit(\n",
    "            *args,\n",
    "            batch_size=hp.Choice(\"batch_size\", [128,256]),\n",
    "            **kwargs,\n",
    "        )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "491e48a4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 16 Complete [00h 00m 35s]\n",
      "val_loss: 0.014558274298906326\n",
      "\n",
      "Best val_loss So Far: 0.013937660492956638\n",
      "Total elapsed time: 00h 08m 11s\n",
      "INFO:tensorflow:Oracle triggered exit\n"
     ]
    }
   ],
   "source": [
    "max_trials = 200\n",
    "train_epochs = 200\n",
    "\n",
    "tuner = keras_tuner.RandomSearch(MyHyperModel(),objective='val_loss',max_trials=max_trials,overwrite=True,)\n",
    "tuner.search([merged_train_firm, merged_train_latent], merged_train_y, \n",
    "             epochs=train_epochs, \n",
    "             validation_data=([merged_val_firm, merged_val_latent], merged_val_y),\n",
    "             callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "78ca7e22",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'l1_ratio': 0.0, 'l2_ratio': 0.0, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 128}\n",
      "{'l1_ratio': 0.0, 'l2_ratio': 0.0, 'dropout': 0.1, 'learning_rate': 5e-05, 'batch_size': 128}\n",
      "{'l1_ratio': 0.0, 'l2_ratio': 0.0, 'dropout': 0.1, 'learning_rate': 0.0001, 'batch_size': 256}\n"
     ]
    }
   ],
   "source": [
    "# 10 Trials for Prediction\n",
    "# 10 Trials for Prediction\n",
    "merged_train_latent_all = np.concatenate((merged_train_latent, merged_val_latent))\n",
    "merged_train_firm_all = np.concatenate((merged_train_firm, merged_val_firm))\n",
    "merged_y_all = np.concatenate((merged_train_y, merged_val_y))\n",
    "best_hps = tuner.get_best_hyperparameters(5)\n",
    "print(best_hps[0].values)\n",
    "print(best_hps[1].values)\n",
    "print(best_hps[2].values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "a68ca49f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0114 - my_metric_fn: 0.0558 - val_loss: 0.0138 - val_my_metric_fn: 0.0092\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0104 - my_metric_fn: 0.1299 - val_loss: 0.0138 - val_my_metric_fn: 0.0042\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0102 - my_metric_fn: 0.1421 - val_loss: 0.0137 - val_my_metric_fn: 0.0077\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0101 - my_metric_fn: 0.1513 - val_loss: 0.0138 - val_my_metric_fn: 3.7343e-04\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0132 - my_metric_fn: 0.0541\n",
      "[0.013186192139983177, 0.05410729721188545]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0113 - my_metric_fn: 0.0587 - val_loss: 0.0139 - val_my_metric_fn: 0.0024\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0104 - my_metric_fn: 0.1290 - val_loss: 0.0138 - val_my_metric_fn: 0.0019\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0102 - my_metric_fn: 0.1435 - val_loss: 0.0138 - val_my_metric_fn: 0.0037\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0101 - my_metric_fn: 0.1523 - val_loss: 0.0137 - val_my_metric_fn: 0.0114\n",
      "Epoch 5/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0100 - my_metric_fn: 0.1579 - val_loss: 0.0137 - val_my_metric_fn: 0.0096\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0132 - my_metric_fn: 0.0594\n",
      "[0.013156007044017315, 0.059370048344135284]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0113 - my_metric_fn: 0.0577 - val_loss: 0.0138 - val_my_metric_fn: 0.0089\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0104 - my_metric_fn: 0.1301 - val_loss: 0.0138 - val_my_metric_fn: 0.0020\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0102 - my_metric_fn: 0.1437 - val_loss: 0.0137 - val_my_metric_fn: 0.0117\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0101 - my_metric_fn: 0.1509 - val_loss: 0.0138 - val_my_metric_fn: 0.0038\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0132 - my_metric_fn: 0.0574\n",
      "[0.013162211515009403, 0.057369478046894073]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0113 - my_metric_fn: 0.0590 - val_loss: 0.0139 - val_my_metric_fn: 7.8615e-04\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0104 - my_metric_fn: 0.1293 - val_loss: 0.0138 - val_my_metric_fn: 0.0021\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0102 - my_metric_fn: 0.1431 - val_loss: 0.0138 - val_my_metric_fn: 0.0062\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0101 - my_metric_fn: 0.1543 - val_loss: 0.0137 - val_my_metric_fn: 0.0057\n",
      "Epoch 5/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0100 - my_metric_fn: 0.1589 - val_loss: 0.0138 - val_my_metric_fn: 0.0023\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0131 - my_metric_fn: 0.0535\n",
      "[0.01312837190926075, 0.053477901965379715]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0114 - my_metric_fn: 0.0468 - val_loss: 0.0139 - val_my_metric_fn: 0.0070\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0104 - my_metric_fn: 0.1263 - val_loss: 0.0139 - val_my_metric_fn: 9.2421e-05\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0102 - my_metric_fn: 0.1419 - val_loss: 0.0138 - val_my_metric_fn: 0.0037\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0101 - my_metric_fn: 0.1517 - val_loss: 0.0138 - val_my_metric_fn: 0.0077\n",
      "Epoch 5/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0100 - my_metric_fn: 0.1593 - val_loss: 0.0137 - val_my_metric_fn: 0.0087\n",
      "Epoch 6/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0100 - my_metric_fn: 0.1636 - val_loss: 0.0137 - val_my_metric_fn: 0.0069\n",
      "Epoch 7/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0099 - my_metric_fn: 0.1652 - val_loss: 0.0137 - val_my_metric_fn: 0.0102\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0132 - my_metric_fn: 0.0534\n",
      "[0.013169826939702034, 0.053377680480480194]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0113 - my_metric_fn: 0.0588 - val_loss: 0.0139 - val_my_metric_fn: 0.0071\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0104 - my_metric_fn: 0.1286 - val_loss: 0.0138 - val_my_metric_fn: 0.0061\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0102 - my_metric_fn: 0.1446 - val_loss: 0.0138 - val_my_metric_fn: 0.0017\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0132 - my_metric_fn: 0.0610\n",
      "[0.013156303204596043, 0.060984399169683456]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0113 - my_metric_fn: 0.0574 - val_loss: 0.0139 - val_my_metric_fn: 0.0043\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0104 - my_metric_fn: 0.1300 - val_loss: 0.0138 - val_my_metric_fn: 0.0050\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0102 - my_metric_fn: 0.1448 - val_loss: 0.0138 - val_my_metric_fn: 0.0056\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0101 - my_metric_fn: 0.1500 - val_loss: 0.0138 - val_my_metric_fn: 0.0048\n",
      "Epoch 5/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0100 - my_metric_fn: 0.1585 - val_loss: 0.0137 - val_my_metric_fn: 0.0111\n",
      "Epoch 6/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0100 - my_metric_fn: 0.1620 - val_loss: 0.0137 - val_my_metric_fn: 0.0040\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0132 - my_metric_fn: 0.0504\n",
      "[0.01316971704363823, 0.05035945028066635]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0113 - my_metric_fn: 0.0590 - val_loss: 0.0138 - val_my_metric_fn: 0.0144\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0104 - my_metric_fn: 0.1306 - val_loss: 0.0138 - val_my_metric_fn: 0.0039\n",
      "2813/2813 [==============================] - 4s 2ms/step - loss: 0.0133 - my_metric_fn: 0.0665\n",
      "[0.01325524877756834, 0.06647898256778717]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0113 - my_metric_fn: 0.0590 - val_loss: 0.0139 - val_my_metric_fn: 0.0058\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0104 - my_metric_fn: 0.1292 - val_loss: 0.0138 - val_my_metric_fn: 0.0050\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0102 - my_metric_fn: 0.1423 - val_loss: 0.0137 - val_my_metric_fn: 0.0066\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0101 - my_metric_fn: 0.1515 - val_loss: 0.0138 - val_my_metric_fn: -7.2213e-04\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0131 - my_metric_fn: 0.0530\n",
      "[0.013142946176230907, 0.0529828704893589]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0114 - my_metric_fn: 0.0574 - val_loss: 0.0139 - val_my_metric_fn: 0.0056\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0104 - my_metric_fn: 0.1311 - val_loss: 0.0139 - val_my_metric_fn: -0.0056\n",
      "2813/2813 [==============================] - 4s 2ms/step - loss: 0.0133 - my_metric_fn: 0.0624\n",
      "[0.013254106976091862, 0.06236640363931656]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "0.16671723048501386\n"
     ]
    }
   ],
   "source": [
    "seed_list = [458, 165, 530, 564, 590, 560, 829, 170, 376, 176]\n",
    "yhat_df = pd.DataFrame()\n",
    "\n",
    "for random_seed in seed_list:\n",
    "    random.seed(random_seed)\n",
    "    np.random.seed(random_seed)\n",
    "    tf.random.set_seed(random_seed)\n",
    "\n",
    "    best_model = tuner.get_best_models(3)[2]\n",
    "    best_model.fit([merged_train_latent, merged_train_firm], merged_train_y,\n",
    "                   epochs=50,\n",
    "                   validation_data=([merged_val_latent, merged_val_firm], merged_val_y),\n",
    "                   callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss',mode='min', patience=1)])\n",
    "    print(best_model.evaluate([merged_test_latent, merged_test_firm], merged_test_y))\n",
    "    y_hat = best_model.predict([merged_test_latent, merged_test_firm]).reshape(-1)\n",
    "    yhat_df[random_seed] = y_hat\n",
    "    print()\n",
    "\n",
    "# Print out Predictive R^2\n",
    "y_predict = yhat_df.mean(axis=1).values.reshape(-1)\n",
    "y_real = merged_test_y\n",
    "\n",
    "a = np.mean(np.square(y_predict -  y_real))\n",
    "b = np.mean(np.square(y_real))\n",
    "print(1-a/b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "b88936fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0125 - my_metric_fn: -0.0402 - val_loss: 0.0144 - val_my_metric_fn: 0.0097\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0118 - my_metric_fn: 0.0269 - val_loss: 0.0138 - val_my_metric_fn: 0.0446\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0111 - my_metric_fn: 0.0879 - val_loss: 0.0136 - val_my_metric_fn: 0.0325\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0107 - my_metric_fn: 0.1106 - val_loss: 0.0137 - val_my_metric_fn: 0.0129\n",
      "2813/2813 [==============================] - 4s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0396\n",
      "[0.013902746140956879, 0.03963005915284157]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0125 - my_metric_fn: -0.0391 - val_loss: 0.0145 - val_my_metric_fn: 0.0091\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0119 - my_metric_fn: 0.0226 - val_loss: 0.0139 - val_my_metric_fn: 0.0394\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0111 - my_metric_fn: 0.0826 - val_loss: 0.0136 - val_my_metric_fn: 0.0339\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0107 - my_metric_fn: 0.1111 - val_loss: 0.0137 - val_my_metric_fn: 0.0150\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0415\n",
      "[0.013878848403692245, 0.041479870676994324]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0125 - my_metric_fn: -0.0399 - val_loss: 0.0145 - val_my_metric_fn: 0.0092\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0119 - my_metric_fn: 0.0242 - val_loss: 0.0138 - val_my_metric_fn: 0.0433\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0111 - my_metric_fn: 0.0887 - val_loss: 0.0136 - val_my_metric_fn: 0.0308\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0107 - my_metric_fn: 0.1110 - val_loss: 0.0137 - val_my_metric_fn: 0.0158\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0417\n",
      "[0.013870828785002232, 0.04174087196588516]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0125 - my_metric_fn: -0.0396 - val_loss: 0.0144 - val_my_metric_fn: 0.0100\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0118 - my_metric_fn: 0.0246 - val_loss: 0.0138 - val_my_metric_fn: 0.0462\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0110 - my_metric_fn: 0.0905 - val_loss: 0.0136 - val_my_metric_fn: 0.0319\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0107 - my_metric_fn: 0.1141 - val_loss: 0.0137 - val_my_metric_fn: 0.0133\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0402\n",
      "[0.013861685059964657, 0.04016318544745445]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0125 - my_metric_fn: -0.0382 - val_loss: 0.0144 - val_my_metric_fn: 0.0108\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0118 - my_metric_fn: 0.0276 - val_loss: 0.0138 - val_my_metric_fn: 0.0437\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0111 - my_metric_fn: 0.0887 - val_loss: 0.0136 - val_my_metric_fn: 0.0311\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0107 - my_metric_fn: 0.1100 - val_loss: 0.0137 - val_my_metric_fn: 0.0170\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0451\n",
      "[0.01387142576277256, 0.04505346342921257]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 9s 3ms/step - loss: 0.0125 - my_metric_fn: -0.0399 - val_loss: 0.0145 - val_my_metric_fn: 0.0083\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0119 - my_metric_fn: 0.0224 - val_loss: 0.0139 - val_my_metric_fn: 0.0394\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0111 - my_metric_fn: 0.0827 - val_loss: 0.0136 - val_my_metric_fn: 0.0335\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0107 - my_metric_fn: 0.1090 - val_loss: 0.0137 - val_my_metric_fn: 0.0169\n",
      "2813/2813 [==============================] - 6s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0446\n",
      "[0.013881489634513855, 0.04461992159485817]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0125 - my_metric_fn: -0.0385 - val_loss: 0.0144 - val_my_metric_fn: 0.0097\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0119 - my_metric_fn: 0.0231 - val_loss: 0.0139 - val_my_metric_fn: 0.0402\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0111 - my_metric_fn: 0.0856 - val_loss: 0.0136 - val_my_metric_fn: 0.0341\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0107 - my_metric_fn: 0.1100 - val_loss: 0.0137 - val_my_metric_fn: 0.0156\n",
      "2813/2813 [==============================] - 4s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0406\n",
      "[0.013891768641769886, 0.04062218219041824]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0125 - my_metric_fn: -0.0381 - val_loss: 0.0144 - val_my_metric_fn: 0.0100\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0118 - my_metric_fn: 0.0261 - val_loss: 0.0138 - val_my_metric_fn: 0.0434\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0111 - my_metric_fn: 0.0907 - val_loss: 0.0136 - val_my_metric_fn: 0.0305\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0107 - my_metric_fn: 0.1115 - val_loss: 0.0136 - val_my_metric_fn: 0.0209\n",
      "Epoch 5/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0106 - my_metric_fn: 0.1197 - val_loss: 0.0137 - val_my_metric_fn: 0.0130\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0138 - my_metric_fn: 0.0416\n",
      "[0.013750642538070679, 0.041637666523456573]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0125 - my_metric_fn: -0.0402 - val_loss: 0.0144 - val_my_metric_fn: 0.0113\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0118 - my_metric_fn: 0.0285 - val_loss: 0.0138 - val_my_metric_fn: 0.0472\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0110 - my_metric_fn: 0.0909 - val_loss: 0.0136 - val_my_metric_fn: 0.0269\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0107 - my_metric_fn: 0.1106 - val_loss: 0.0137 - val_my_metric_fn: 0.0133\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0415\n",
      "[0.01387670636177063, 0.04146427661180496]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 7s 2ms/step - loss: 0.0125 - my_metric_fn: -0.0392 - val_loss: 0.0144 - val_my_metric_fn: 0.0106\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0118 - my_metric_fn: 0.0270 - val_loss: 0.0138 - val_my_metric_fn: 0.0417\n",
      "Epoch 3/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0111 - my_metric_fn: 0.0883 - val_loss: 0.0136 - val_my_metric_fn: 0.0313\n",
      "Epoch 4/50\n",
      "2761/2761 [==============================] - 6s 2ms/step - loss: 0.0107 - my_metric_fn: 0.1116 - val_loss: 0.0137 - val_my_metric_fn: 0.0159\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0437\n",
      "[0.013856420293450356, 0.04366641491651535]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "0.12049795180438982\n"
     ]
    }
   ],
   "source": [
    "seed_list = [458, 165, 530, 564, 590, 560, 829, 170, 376, 176]\n",
    "yhat_df = pd.DataFrame()\n",
    "\n",
    "for random_seed in seed_list:\n",
    "    random.seed(random_seed)\n",
    "    np.random.seed(random_seed)\n",
    "    tf.random.set_seed(random_seed)\n",
    "\n",
    "    best_model = tuner.get_best_models(3)[1]\n",
    "    best_model.fit([merged_train_latent, merged_train_firm], merged_train_y,\n",
    "                   epochs=50,\n",
    "                   validation_data=([merged_val_latent, merged_val_firm], merged_val_y),\n",
    "                   callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss',mode='min', patience=1)])\n",
    "    print(best_model.evaluate([merged_test_latent, merged_test_firm], merged_test_y))\n",
    "    y_hat = best_model.predict([merged_test_latent, merged_test_firm]).reshape(-1)\n",
    "    yhat_df[random_seed] = y_hat\n",
    "    print()\n",
    "\n",
    "# Print out Predictive R^2\n",
    "y_predict = yhat_df.mean(axis=1).values.reshape(-1)\n",
    "y_real = merged_test_y\n",
    "\n",
    "a = np.mean(np.square(y_predict -  y_real))\n",
    "b = np.mean(np.square(y_real))\n",
    "print(1-a/b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1006660a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e88e7c27",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "8da7675a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def my_metric_fn(y_true, y_pred):\n",
    "    num = tf.reduce_mean(tf.square(y_true - y_pred))\n",
    "    den = tf.reduce_mean(tf.square(y_true))\n",
    "    return 1 - num / den\n",
    "\n",
    "\n",
    "def build(n_inputs=49,):\n",
    "    l1_reg = 0.0\n",
    "    l2_reg = 0.0\n",
    "    dropout = 0.0\n",
    "    lr = 0.0001\n",
    "        \n",
    "    # Define the hidden layers \n",
    "    input1 = Input(shape=(49,))\n",
    "    x1 = Dense(6, activation='relu')(input1)\n",
    "        \n",
    "    # Input 2\n",
    "    input2 = Input(shape=(49,))\n",
    "    x2 = Dense(32, activation='relu',kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(input2)\n",
    "    x2 = Dense(16, activation='relu',kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(x2)\n",
    "    #x2 = Dense(8, activation='relu', kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(x2)\n",
    "    x2 = Dense(6, activation='relu', kernel_regularizer=l1_l2(l1=l1_reg,l2=l2_reg))(x2)\n",
    "        \n",
    "    merged = Multiply()([x1, x2])\n",
    "    output = Dense(1, activation='linear')(merged)\n",
    " \n",
    "    # Create the model \n",
    "    model = Model(inputs=[input1, input2], outputs=output)\n",
    "    opt = tf.keras.optimizers.Adam(learning_rate=lr)\n",
    "    model.compile(loss='mean_squared_error', optimizer=opt,metrics=[my_metric_fn])\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "527fb86e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/30\n",
      "691/691 [==============================] - 6s 6ms/step - loss: 0.0119 - my_metric_fn: 0.0239 - val_loss: 0.0142 - val_my_metric_fn: 0.0222\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 4s 6ms/step - loss: 0.0114 - my_metric_fn: 0.0602 - val_loss: 0.0141 - val_my_metric_fn: 0.0209\n",
      "Epoch 3/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0111 - my_metric_fn: 0.0834 - val_loss: 0.0141 - val_my_metric_fn: 0.0160\n",
      "Epoch 4/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0109 - my_metric_fn: 0.1013 - val_loss: 0.0141 - val_my_metric_fn: 0.0116\n",
      "2813/2813 [==============================] - 9s 3ms/step - loss: 0.0140 - my_metric_fn: 0.0374\n",
      "[0.014004412107169628, 0.03736567124724388]\n",
      "2813/2813 [==============================] - 9s 3ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 5s 6ms/step - loss: 0.0119 - my_metric_fn: 0.0205 - val_loss: 0.0142 - val_my_metric_fn: 0.0254\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 3s 4ms/step - loss: 0.0113 - my_metric_fn: 0.0763 - val_loss: 0.0140 - val_my_metric_fn: 0.0295\n",
      "Epoch 3/30\n",
      "691/691 [==============================] - 3s 4ms/step - loss: 0.0108 - my_metric_fn: 0.1179 - val_loss: 0.0139 - val_my_metric_fn: 0.0266\n",
      "Epoch 4/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0105 - my_metric_fn: 0.1397 - val_loss: 0.0139 - val_my_metric_fn: 0.0263\n",
      "Epoch 5/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0103 - my_metric_fn: 0.1547 - val_loss: 0.0139 - val_my_metric_fn: 0.0277\n",
      "Epoch 6/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0101 - my_metric_fn: 0.1660 - val_loss: 0.0139 - val_my_metric_fn: 0.0224\n",
      "2813/2813 [==============================] - 10s 4ms/step - loss: 0.0136 - my_metric_fn: 0.0564\n",
      "[0.01361942384392023, 0.05637696385383606]\n",
      "2813/2813 [==============================] - 9s 3ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 5s 6ms/step - loss: 0.0119 - my_metric_fn: 0.0239 - val_loss: 0.0142 - val_my_metric_fn: 0.0218\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0114 - my_metric_fn: 0.0595 - val_loss: 0.0141 - val_my_metric_fn: 0.0194\n",
      "Epoch 3/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0111 - my_metric_fn: 0.0841 - val_loss: 0.0141 - val_my_metric_fn: 0.0208\n",
      "Epoch 4/30\n",
      "691/691 [==============================] - 4s 6ms/step - loss: 0.0109 - my_metric_fn: 0.1061 - val_loss: 0.0140 - val_my_metric_fn: 0.0221\n",
      "Epoch 5/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0106 - my_metric_fn: 0.1265 - val_loss: 0.0139 - val_my_metric_fn: 0.0196\n",
      "Epoch 6/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0104 - my_metric_fn: 0.1450 - val_loss: 0.0140 - val_my_metric_fn: 0.0158\n",
      "2813/2813 [==============================] - 9s 3ms/step - loss: 0.0137 - my_metric_fn: 0.0454\n",
      "[0.013724006712436676, 0.04540223628282547]\n",
      "2813/2813 [==============================] - 7s 2ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 5s 6ms/step - loss: 0.0121 - my_metric_fn: 0.0079 - val_loss: 0.0144 - val_my_metric_fn: 0.0159\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0118 - my_metric_fn: 0.0287 - val_loss: 0.0143 - val_my_metric_fn: 0.0215\n",
      "Epoch 3/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0115 - my_metric_fn: 0.0530 - val_loss: 0.0142 - val_my_metric_fn: 0.0219\n",
      "Epoch 4/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0112 - my_metric_fn: 0.0733 - val_loss: 0.0142 - val_my_metric_fn: 0.0220\n",
      "Epoch 5/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0111 - my_metric_fn: 0.0879 - val_loss: 0.0141 - val_my_metric_fn: 0.0205\n",
      "Epoch 6/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0109 - my_metric_fn: 0.1006 - val_loss: 0.0141 - val_my_metric_fn: 0.0210\n",
      "Epoch 7/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0108 - my_metric_fn: 0.1117 - val_loss: 0.0141 - val_my_metric_fn: 0.0167\n",
      "2813/2813 [==============================] - 9s 3ms/step - loss: 0.0136 - my_metric_fn: 0.0649\n",
      "[0.013625040650367737, 0.06489545851945877]\n",
      "2813/2813 [==============================] - 7s 2ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 5s 6ms/step - loss: 0.0118 - my_metric_fn: 0.0326 - val_loss: 0.0141 - val_my_metric_fn: 0.0259\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 4s 6ms/step - loss: 0.0111 - my_metric_fn: 0.0857 - val_loss: 0.0141 - val_my_metric_fn: 0.0153\n",
      "2813/2813 [==============================] - 10s 3ms/step - loss: 0.0144 - my_metric_fn: 0.0361\n",
      "[0.01437702402472496, 0.03606625646352768]\n",
      "2813/2813 [==============================] - 8s 3ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 5s 6ms/step - loss: 0.0119 - my_metric_fn: 0.0247 - val_loss: 0.0144 - val_my_metric_fn: 0.0118\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0115 - my_metric_fn: 0.0542 - val_loss: 0.0144 - val_my_metric_fn: 0.0075\n",
      "2813/2813 [==============================] - 10s 4ms/step - loss: 0.0146 - my_metric_fn: 0.0335\n",
      "[0.014618124812841415, 0.03345658257603645]\n",
      "2813/2813 [==============================] - 8s 3ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 5s 6ms/step - loss: 0.0118 - my_metric_fn: 0.0265 - val_loss: 0.0143 - val_my_metric_fn: 0.0197\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 3s 4ms/step - loss: 0.0114 - my_metric_fn: 0.0639 - val_loss: 0.0142 - val_my_metric_fn: 0.0213\n",
      "Epoch 3/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0111 - my_metric_fn: 0.0906 - val_loss: 0.0141 - val_my_metric_fn: 0.0197\n",
      "Epoch 4/30\n",
      "691/691 [==============================] - 3s 5ms/step - loss: 0.0109 - my_metric_fn: 0.1063 - val_loss: 0.0141 - val_my_metric_fn: 0.0190\n",
      "Epoch 5/30\n",
      "691/691 [==============================] - 4s 6ms/step - loss: 0.0107 - my_metric_fn: 0.1210 - val_loss: 0.0140 - val_my_metric_fn: 0.0222\n",
      "Epoch 6/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0106 - my_metric_fn: 0.1321 - val_loss: 0.0141 - val_my_metric_fn: 0.0162\n",
      "2813/2813 [==============================] - 9s 3ms/step - loss: 0.0141 - my_metric_fn: 0.0459\n",
      "[0.014077228493988514, 0.04590607061982155]\n",
      "2813/2813 [==============================] - 9s 3ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 5s 6ms/step - loss: 0.0117 - my_metric_fn: 0.0360 - val_loss: 0.0139 - val_my_metric_fn: 0.0385\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 4s 5ms/step - loss: 0.0111 - my_metric_fn: 0.0877 - val_loss: 0.0139 - val_my_metric_fn: 0.0324\n",
      "Epoch 3/30\n",
      "691/691 [==============================] - 4s 6ms/step - loss: 0.0107 - my_metric_fn: 0.1162 - val_loss: 0.0138 - val_my_metric_fn: 0.0344\n",
      "Epoch 4/30\n",
      "691/691 [==============================] - 3s 4ms/step - loss: 0.0105 - my_metric_fn: 0.1366 - val_loss: 0.0139 - val_my_metric_fn: 0.0210\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0140 - my_metric_fn: 0.0412\n",
      "[0.013981676660478115, 0.041244421154260635]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 2s 3ms/step - loss: 0.0119 - my_metric_fn: 0.0213 - val_loss: 0.0141 - val_my_metric_fn: 0.0312\n",
      "Epoch 2/30\n",
      "691/691 [==============================] - 2s 3ms/step - loss: 0.0114 - my_metric_fn: 0.0625 - val_loss: 0.0139 - val_my_metric_fn: 0.0293\n",
      "Epoch 3/30\n",
      "691/691 [==============================] - 2s 3ms/step - loss: 0.0110 - my_metric_fn: 0.0963 - val_loss: 0.0139 - val_my_metric_fn: 0.0284\n",
      "Epoch 4/30\n",
      "691/691 [==============================] - 2s 3ms/step - loss: 0.0106 - my_metric_fn: 0.1249 - val_loss: 0.0138 - val_my_metric_fn: 0.0249\n",
      "Epoch 5/30\n",
      "691/691 [==============================] - 2s 3ms/step - loss: 0.0104 - my_metric_fn: 0.1462 - val_loss: 0.0138 - val_my_metric_fn: 0.0208\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0137 - my_metric_fn: 0.0597\n",
      "[0.013712115585803986, 0.059708744287490845]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "Epoch 1/30\n",
      "691/691 [==============================] - 3s 3ms/step - loss: 0.0119 - my_metric_fn: 0.0182 - val_loss: 0.0142 - val_my_metric_fn: 0.0259\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 2/30\n",
      "691/691 [==============================] - 2s 2ms/step - loss: 0.0111 - my_metric_fn: 0.0916 - val_loss: 0.0139 - val_my_metric_fn: 0.0274\n",
      "Epoch 3/30\n",
      "691/691 [==============================] - 2s 2ms/step - loss: 0.0105 - my_metric_fn: 0.1363 - val_loss: 0.0139 - val_my_metric_fn: 0.0255\n",
      "Epoch 4/30\n",
      "691/691 [==============================] - 2s 2ms/step - loss: 0.0103 - my_metric_fn: 0.1558 - val_loss: 0.0140 - val_my_metric_fn: 0.0143\n",
      "2813/2813 [==============================] - 4s 1ms/step - loss: 0.0140 - my_metric_fn: 0.0390\n",
      "[0.01399341318756342, 0.038965798914432526]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n"
     ]
    }
   ],
   "source": [
    "seed_list = [458, 165, 530, 564, 590, 560, 829, 170, 376, 176]\n",
    "yhat_df = pd.DataFrame()\n",
    "# 10 Trials for Prediction\n",
    "merged_train_latent_all = np.concatenate((merged_train_latent, merged_val_latent))\n",
    "merged_train_firm_all = np.concatenate((merged_train_firm, merged_val_firm))\n",
    "merged_y_all = np.concatenate((merged_train_y, merged_val_y))\n",
    "\n",
    "for random_seed in seed_list:\n",
    "    random.seed(random_seed)\n",
    "    np.random.seed(random_seed)\n",
    "    tf.random.set_seed(random_seed)\n",
    "\n",
    "    model = build()\n",
    "    model.fit([merged_train_firm, merged_train_latent], merged_train_y,\n",
    "              validation_data=([merged_val_firm, merged_val_latent], merged_val_y),\n",
    "              epochs=30,\n",
    "              batch_size = 128,\n",
    "              callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss',mode='min', patience=1)]\n",
    "              )\n",
    "    print(model.evaluate([merged_test_firm, merged_test_latent], merged_test_y))\n",
    "    y_hat = model.predict([merged_test_firm, merged_test_latent]).reshape(-1)\n",
    "    yhat_df[random_seed] = y_hat\n",
    "    print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "e628019b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.16251541798093383\n"
     ]
    }
   ],
   "source": [
    "# Print out Predictive R^2\n",
    "y_predict = yhat_df.mean(axis=1).values.reshape(-1)\n",
    "y_real = merged_test_y\n",
    "\n",
    "a = np.mean(np.square(y_predict -  y_real))\n",
    "b = np.mean(np.square(y_real))\n",
    "print(1-a/b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "07049dda",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 2 Complete [00h 00m 13s]\n",
      "val_loss: 0.01379997469484806\n",
      "\n",
      "Best val_loss So Far: 0.01379997469484806\n",
      "Total elapsed time: 00h 00m 28s\n",
      "INFO:tensorflow:Oracle triggered exit\n"
     ]
    }
   ],
   "source": [
    "max_trials = 200\n",
    "train_epochs = 200\n",
    "\n",
    "tuner = keras_tuner.RandomSearch(MyHyperModel(),objective='val_loss',max_trials=max_trials,overwrite=True,)\n",
    "tuner.search([merged_train_firm, merged_train_latent], merged_train_y, \n",
    "             epochs=train_epochs, \n",
    "             validation_data=([merged_val_firm, merged_val_latent], merged_val_y),\n",
    "             callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "bf899e5c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'l1_ratio': 0.0, 'l2_ratio': 0.0, 'dropout': 0.0, 'learning_rate': 0.0001, 'batch_size': 256}\n",
      "{'l1_ratio': 0.0, 'l2_ratio': 0.0, 'dropout': 0.0, 'learning_rate': 0.0001, 'batch_size': 128}\n",
      "{'l1_ratio': 0.0, 'l2_ratio': 0.0, 'dropout': 0.0, 'learning_rate': 0.001, 'batch_size': 256}\n"
     ]
    }
   ],
   "source": [
    "# 10 Trials for Prediction\n",
    "# 10 Trials for Prediction\n",
    "merged_train_latent_all = np.concatenate((merged_train_latent, merged_val_latent))\n",
    "merged_train_firm_all = np.concatenate((merged_train_firm, merged_val_firm))\n",
    "merged_y_all = np.concatenate((merged_train_y, merged_val_y))\n",
    "best_hps = tuner.get_best_hyperparameters(5)\n",
    "print(best_hps[0].values)\n",
    "print(best_hps[1].values)\n",
    "print(best_hps[2].values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "12287e07",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0117 - my_metric_fn: 0.0266 - val_loss: 0.0138 - val_my_metric_fn: 0.0302\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0108 - my_metric_fn: 0.1086 - val_loss: 0.0142 - val_my_metric_fn: -0.0137\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0475\n",
      "[0.013854393735527992, 0.04747656360268593]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0117 - my_metric_fn: 0.0270 - val_loss: 0.0139 - val_my_metric_fn: 0.0267\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 10s 4ms/step - loss: 0.0108 - my_metric_fn: 0.1063 - val_loss: 0.0141 - val_my_metric_fn: -0.0108\n",
      "2813/2813 [==============================] - 8s 3ms/step - loss: 0.0139 - my_metric_fn: 0.0494\n",
      "[0.013876578770577908, 0.04936505854129791]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0118 - my_metric_fn: 0.0247 - val_loss: 0.0138 - val_my_metric_fn: 0.0319\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0108 - my_metric_fn: 0.1079 - val_loss: 0.0142 - val_my_metric_fn: -0.0141\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0138 - my_metric_fn: 0.0477\n",
      "[0.013845900073647499, 0.04765352979302406]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0117 - my_metric_fn: 0.0246 - val_loss: 0.0139 - val_my_metric_fn: 0.0268\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0108 - my_metric_fn: 0.1059 - val_loss: 0.0142 - val_my_metric_fn: -0.0183\n",
      "2813/2813 [==============================] - 6s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0458\n",
      "[0.013904206454753876, 0.04583529382944107]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0117 - my_metric_fn: 0.0242 - val_loss: 0.0139 - val_my_metric_fn: 0.0303\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0108 - my_metric_fn: 0.1066 - val_loss: 0.0142 - val_my_metric_fn: -0.0123\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0488\n",
      "[0.013875019736588001, 0.04881473258137703]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 10s 3ms/step - loss: 0.0117 - my_metric_fn: 0.0256 - val_loss: 0.0138 - val_my_metric_fn: 0.0300\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0108 - my_metric_fn: 0.1063 - val_loss: 0.0141 - val_my_metric_fn: -0.0094\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0489\n",
      "[0.013862303458154202, 0.04894855618476868]\n",
      "2813/2813 [==============================] - 4s 1ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0117 - my_metric_fn: 0.0285 - val_loss: 0.0139 - val_my_metric_fn: 0.0272\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0107 - my_metric_fn: 0.1083 - val_loss: 0.0141 - val_my_metric_fn: -0.0112\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0138 - my_metric_fn: 0.0481\n",
      "[0.013845184817910194, 0.04809502512216568]\n",
      "2813/2813 [==============================] - 4s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0117 - my_metric_fn: 0.0283 - val_loss: 0.0138 - val_my_metric_fn: 0.0306\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 7s 3ms/step - loss: 0.0108 - my_metric_fn: 0.1073 - val_loss: 0.0141 - val_my_metric_fn: -0.0113\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0492\n",
      "[0.013868139125406742, 0.049201615154743195]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0117 - my_metric_fn: 0.0262 - val_loss: 0.0139 - val_my_metric_fn: 0.0292\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0108 - my_metric_fn: 0.1076 - val_loss: 0.0141 - val_my_metric_fn: -0.0095\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0138 - my_metric_fn: 0.0503\n",
      "[0.013844025321304798, 0.05025520920753479]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate\n",
      "Epoch 1/50\n",
      "2761/2761 [==============================] - 9s 3ms/step - loss: 0.0118 - my_metric_fn: 0.0237 - val_loss: 0.0139 - val_my_metric_fn: 0.0306\n",
      "Epoch 2/50\n",
      "2761/2761 [==============================] - 8s 3ms/step - loss: 0.0108 - my_metric_fn: 0.1076 - val_loss: 0.0142 - val_my_metric_fn: -0.0182\n",
      "2813/2813 [==============================] - 5s 2ms/step - loss: 0.0139 - my_metric_fn: 0.0472\n",
      "[0.013890499249100685, 0.04720933735370636]\n",
      "2813/2813 [==============================] - 5s 2ms/step\n",
      "\n",
      "0.12028645968794716\n"
     ]
    }
   ],
   "source": [
    "seed_list = [458, 165, 530, 564, 590, 560, 829, 170, 376, 176]\n",
    "yhat_df = pd.DataFrame()\n",
    "\n",
    "for random_seed in seed_list:\n",
    "    random.seed(random_seed)\n",
    "    np.random.seed(random_seed)\n",
    "    tf.random.set_seed(random_seed)\n",
    "\n",
    "    best_model = tuner.get_best_models(3)[0]\n",
    "    best_model.fit([merged_train_latent, merged_train_firm], merged_train_y,\n",
    "                   epochs=50,\n",
    "                   validation_data=([merged_val_latent, merged_val_firm], merged_val_y),\n",
    "                   callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss',mode='min', patience=1)])\n",
    "    print(best_model.evaluate([merged_test_latent, merged_test_firm], merged_test_y))\n",
    "    y_hat = best_model.predict([merged_test_latent, merged_test_firm]).reshape(-1)\n",
    "    yhat_df[random_seed] = y_hat\n",
    "    print()\n",
    "\n",
    "# Print out Predictive R^2\n",
    "y_predict = yhat_df.mean(axis=1).values.reshape(-1)\n",
    "y_real = merged_test_y\n",
    "\n",
    "a = np.mean(np.square(y_predict -  y_real))\n",
    "b = np.mean(np.square(y_real))\n",
    "print(1-a/b)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
